name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive # 同时克隆子模块
        fetch-depth: 0        # 完整克隆仓库历史
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
    - name: List output APK files
      run: find ./app/build/outputs/apk/nonRoot/release/ -type f
    - run: mv ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release-unsigned.apk moonlight.apk
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.apk"
        token: ${{ github.token }}
        generateReleaseNotes: true
